name: RT535xmpp1

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Installation depends
      run: |
        sudo mkdir -p /home/user/lede-a5v11-dl
        sudo mkdir -p /home/user/sandbox
        cd /home/user/sandbox
        sudo svn co http://github.com/hackboxguy/lede-a5v11
        cd /home/user/sandbox/lede-a5v11/trunk
        sudo ln -s /home/user/sandbox/lede-a5v11-dl lede-dl
        sudo cp brbox-sources/* /home/user/lede-a5v11-dl/
        sudo ./prepare.sh
       # sudo ./build.sh -o /mnt/buildramdisk -v 00.01 -b a5v11-xmpp
        sudo ./build.sh -o /home/user -v 00.01 -b a5v11-xmpp
    - uses: actions/upload-artifact@v2
      with:
        name: RT5350xmpp
        path: /home/runner/work/sandbox/lede-a5v11/trunk/source/bin/targets/ramips/rt305x/openwrt-ramips-rt305x-a5-v11-squashfs-sysupgrade.bin

      
